### ISSUE TITLE
Docker-compose to build a full Grid backend stack

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/grid_deployment#1]
## Why
It should be easy for anyone to setup all the services required to host a complete Grid V3 backend. Anyone using these services should have all the tools to fully utilize the Grid.

## Goal
A well prepared docker-compose package that will setup all required services with minimal user input, largely automated. Simple to setup, use and monitor.

## Components - service management
- Docker-compose
- Core X (https://github.com/threefoldtech/corex)

## Components - services
- TFchain public node
- Graphql stack (Indexer, Processor, redis and Postgresql)
- Gridproxy
- Yggdrasil (Gridproxy)
- Activation service
- Dashboard
- Weblets (playground)

## Requirements
- Simple installation
- Minimal operational overhead
- Have each service running as fast as possible (data snapshots)
- User documentation
- A way to check the service status

## Caddy - DNS
Several services need to be exposed via a dns record, so one can interact with the hosted websites (Dashboard & Playground). These websites in turn need to be able to access (from the user browser) the TFchain public node, Graphql and Grixproxy hosted by this package. Every record needs a valid TLS certificate via Let's Encrypt. This will be a story on it's own.

## Metrics
Exposing Prometheus metrics on the services will provide state monitoring. We can later build upon this to include a monitoring service and alerting. Or an integration with Vector and https://metrics.grid.tf

## Remarks
Sync time of the public node, indexer and processor is too long. The chain is currently ~60GB so this would take weeks to sync, index and process. Providing snapshots could be a good first approach to shorten the time to be operational. We could test and provide weekly snapshots of the chain data plus indexer / processor postgres database. This will be another story.

Docker-compose should allow for upgrading deployed containers. Automatic upgrade could also be build in though in it's first phase a user will have to initiate an upgrade manually.

## TODO

- [x] #2 
- [ ] Make docker container images available for all components/services:
  - [ ] tfchain:
    - [ ] Tfchain node ( repo: [tfchain](https://github.com/threefoldtech/tfchain), currently manual process to docker hub (`threefolddev/tfchain`) ). Issue to publish to ghcr:
      - [ ] [Add github action that builds an image when a tag is released](https://github.com/threefoldtech/tfchain/issues/517)  
    - [x]  Graphql stack:
      - [x] Indexer ( subsquid/hydra-indexer:5, subsquid/hydra-indexer-gateway:5, subsquid/hydra-indexer-status-service:5, redis:6.0-alpine, postgres:12 ) -> no custom images needed
      - [x] Processor: not published, multistage Dockerfile available at the root of repo, processor and querynode targets should be specified, currently the commands are set in k8s helm charts and the available docker compose file. Issue:
        - [x] [Publish container images through github packages](https://github.com/threefoldtech/tfchain_graphql/issues/80) 
   - [x] gridproxy: docker hub: `threefolddev/gridproxy`
   - [x] Activation service: repo: [tfchain_activation_service](https://github.com/threefoldtech/tfchain_activation_service), not published, Dockerfile available at the root of the repo. Issue: 
     - [x] [Publish a docker image through github packages](https://github.com/threefoldtech/tfchain_activation_service/issues/16)
   - [x] Dashboard: repo: [tfgrid_dashboard](https://github.com/threefoldtech/tfgrid_dashboard), currently on docker hub (`threefolddev/tfgrid_dashboard`) via github workflow
   - [x] Play ( repo: [grid_weblets](https://github.com/threefoldtech/grid_weblets) currently on docker hub `threefolddev/grid_weblets` via github workflow )  
 - [ ] Assemble the services in a docker compose file

**Comment by coesensbert** [comment]
A first version can be found here: https://github.com/threefoldtech/grid_deployment/blob/development/docker-compose/docker-compose.yml

**Comment by coesensbert** [comment]
A backend setup using this docker-compose can be tested. The ava.tf domain is configured with our own Cetus nameservers, so it's a good playground to start building the new DNS backend also.

Devnet:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2F%2Ftfchain.bknd1.dev.ava.tf#/explorer
https://graphql.bknd1.dev.ava.tf/graphql
https://activation.bknd1.dev.ava.tf/
https://gridproxy.bknd1.dev.ava.tf/
https://dashboard.bknd1.dev.ava.tf/ (still has env var issues, not pointing to the correct backend urls)
https://play.bknd1.dev.ava.tf/#/ (still has env var issues, not pointing to the correct backend urls)

**Comment by robvanmieghem** [comment]
deprecated by https://github.com/threefoldtech/builders/tree/master/compose/tfgrid
